purge

%% Set subject variables
% subject_label = 'Price_241319_fMRI_mb3_229iso';
% proc_dir = '/Volumes/NBL_Projects/DenseSampling/Subject_Data/sub-DS901/ses-1/mri/Price_241319/NIFTI';
% raw_dir = proc_dir;
% anat_nii_name =  [raw_dir '/Price_241319.06.01.14-33-20.WIP_T1_MPRAGE.01.nii'];
% func_nii_name =  [raw_dir '/Price_241319.23.01.15-54-58.WIP_fMRI_mb3_229iso.01.nii'];
% revPE_nii_name = [raw_dir '/Price_241319.24.01.16-04-35.WIP_fMRI_mb3_229iso_APA.01.nii'];
% slice_timing_name = [proc_dir '/slice_order_AFNI_oddsevens_mb3_1.9383TR_54slices.txt'];

subject_label = 'Price_241319_fMRI_mb4_229iso';
proc_dir = '/Volumes/NBL_Projects/DenseSampling/Subject_Data/sub-DS901/ses-1/mri/Price_241319/NIFTI';
raw_dir = proc_dir;
anat_nii_name =  [raw_dir '/Price_241319.06.01.14-33-20.WIP_T1_MPRAGE.01.nii'];
func_nii_name =  [raw_dir '/Price_241319.25.01.16-06-00.WIP_fMRI_mb4_229iso.01.nii'];
revPE_nii_name = [raw_dir '/Price_241319.26.01.16-09-25.WIP_fMRI_mb4_229iso_APA.01.nii'];
slice_timing_name = [proc_dir '/slice_order_AFNI_oddsevens_mb4_0.9638TR_52slices.txt'];

% Write command window output to text file
diary(['output.' subject_label]);

%% Create process pipeline script
% Resting state analysis in native anatomical space
unix(['afni_proc.py -subj_id ' subject_label ...
        ' -dsets ' func_nii_name ...
        ' -blip_reverse_dset ' revPE_nii_name ...
        ' -blocks despike tshift align volreg blur mask regress'...
        ' -copy_anat ' anat_nii_name ...
        ' -tshift_opts_ts -verbose -tpattern @' slice_timing_name...
        ' -align_opts_aea -giant_move -cost lpc+ZZ'...
        ' -volreg_align_e2a'...
        ' -volreg_align_to MIN_OUTLIER'...
        ' -volreg_compute_tsnr yes'...
        ' -mask_segment_anat yes'...
        ' -mask_segment_erode yes'...
        ' -blur_size 6'...
        ' -regress_motion_per_run'...
        ' -regress_apply_mot_types demean deriv'...
        ' -regress_anaticor_fast'...
        ' -regress_ROI_PC WMe 3'...
        ' -regress_censor_motion 0.3'...  
        ' -regress_censor_outliers 0.05'...
        ' -regress_bandpass 0.01 0.1'... 
        ' -regress_motion_per_run'...
        ' -regress_apply_mot_types demean deriv'...
        ' -regress_run_clustsim no'...
        ' -html_review_style pythonic']);

%% Run AFNI Proc script
proc_script = dir(['proc.' subject_label]);
unix(['tcsh -xef ' proc_script(1).name]); 

%% Calculate mean TSNR after volreg, save to text file
cd([subject_label '.results']);
unix('3dmaskave -quiet -mask full_mask*.HEAD TSNR.vreg*.HEAD > TSNR.vreg.mean.txt');

%% Turn off writing to text file
diary off