function [afni_proc_cmd] = DDK2_generate_proc_script(subj,year,orig_dir,raw_data_files,proc_dir,onsets_dir,temp_dir)
%% This function creates the process script, calling afni_proc.py
%% Price DDK2 IsItANumber Task
%% Preprocessing Script
% by Benjamin Neal Conrad, January 2020
% Vanderbilt University

%% Add AFNI binary files to path
%addpath(genpath('/Users/benconrad/Desktop/Price7T/matfiles/'));
add_AFNI_to_path;

%% Subject label
sid = [subj '_' year];
r = raw_data_files;
cd(orig_dir)

%% Set up filename variables
% Anat (with check for alternate acquisition)
anat_nii = strcat(r.anat_fname{1},'.gz');
% Functional nii
func_nii = strjoin(strcat(r.func_fname,'.gz'));
% APA (with check that it exists)
apa_nii = strjoin(strcat(r.apa_fname(1),'.gz'));
if size(dir(apa_nii),1) == 0
    blip_dset = '';
elseif size(dir(apa_nii),1) >= 1 % Accounts for additional hidden files starting with .
    blip_dset = [' -blip_reverse_dset ' apa_nii];
end

% Onset files
onsets_txt = [onsets_dir '/*Digit.txt '...
              onsets_dir '/*Dots.txt '...
              onsets_dir '/*Letter.txt '...
              onsets_dir '/*Novel.txt '...
              onsets_dir '/*Error.txt '...
              onsets_dir '/*Omission.txt'];
stim_labels = 'Dig Dot Let Nov error omiss';

% Slice timing file (account for server location in either Ubuntu VM or OSX)
slice_timing_txt = '/mnt/NSF_SNP/matfiles/preprocessing_pipeline/slice_order_SNP_MB2_40slices_interleaved_AFNI.txt';
if ~exist(slice_timing_txt,'file')
    slice_timing_txt = '/Volumes/NBL_Projects/NSF_SNP/matfiles/preprocessing_pipeline/slice_order_SNP_MB2_40slices_interleaved_AFNI.txt';
end
if ~exist(slice_timing_txt,'file')
    error('Cannot find slice timing file!!')
end

%% Actually run afni_proc.py
% This program sets up the full processing pipeline script
afni_proc_cmd = ['afni_proc.py -subj_id ' sid...
        ' -out_dir ' temp_dir '/' sid '.results' ...
        ' -dsets ' func_nii ' ' blip_dset...
        ' -blocks despike tshift align tlrc volreg blur mask scale regress'...
        ' -copy_anat ' anat_nii...
        ' -tshift_opts_ts -verbose -tpattern @' slice_timing_txt...
        ' -blip_opts_qw -resample'...
        ' -align_opts_aea -giant_move -cost lpc+ZZ'...
        ' -tlrc_base ~/abin/HaskinsPeds_NL_template1.0+tlrc.BRIK.gz'...
        ' -tlrc_NL_warp'...
        ' -tlrc_opts_at -qw_opts -lite'...
        ' -volreg_align_to MIN_OUTLIER'...
        ' -volreg_tlrc_warp'...
        ' -volreg_warp_dxyz 2.5'...
        ' -volreg_compute_tsnr yes'...
        ' -mask_segment_anat yes'...
        ' -mask_segment_erode yes'...
        ' -blur_size 6'...
        ' -regress_stim_times ' onsets_txt...
        ' -regress_stim_labels ' stim_labels...
        ' -regress_basis "GAM(8.6,.547,2)"'...
        ' -regress_local_times'...
        ' -regress_censor_motion 0.5'...  
        ' -regress_censor_outliers 0.1'...
        ' -regress_apply_mot_types demean deriv'...
        ' -regress_motion_per_run'...
        ' -regress_ROI_PC WMe 3'...
        ' -regress_opts_3dD'...
        '    -bout'...
        '    -jobs 15'...
        '    -allzero_OK'...
        '    -GOFORIT 5'...
        '    -num_glt 12'...
        '    -gltsym "SYM: +Dig -Dot" -glt_label 1 Dig-Dot'...
        '    -gltsym "SYM: +Dig -Let" -glt_label 2 Dig-Let'...
        '    -gltsym "SYM: +Dig -Nov" -glt_label 3 Dig-Nov'...
        '    -gltsym "SYM: +Dot -Let" -glt_label 4 Dot-Let'...
        '    -gltsym "SYM: +Dot -Nov" -glt_label 5 Dot-Nov'...
        '    -gltsym "SYM: +Let -Nov" -glt_label 6 Let-Nov'...
        '    -gltsym "SYM: +0.5*Dig +0.5*Dot -0.5*Let -0.5*Nov" -glt_label 7 Num-Non'...
        '    -gltsym "SYM: +Dig -0.5*Let -0.5*Nov" -glt_label 8 Dig-L+N'...
        '    -gltsym "SYM: +Dot -0.5*Let -0.5*Nov" -glt_label 9 Dot-L+N'...
        '    -gltsym "SYM: +0.5*Dig +0.5*Dot -Let" -glt_label 10 Num-Let'...
        '    -gltsym "SYM: +0.5*Dig +0.5*Dot -Nov" -glt_label 11 Num-Nov'...
        '    -gltsym "SYM: +0.5*Dig +0.5*Let -Nov" -glt_label 12 Fml-Nov'...
        ' -regress_reml_exec'...
        ' -regress_opts_reml -GOFORIT -Rwherr errts.' sid '_REMLwh'...
        ' -regress_run_clustsim yes'...
        ' -regress_est_blur_epits'...
        ' -regress_est_blur_errts'...
        ' -radial_correlate_blocks tcat volreg scale'...
        ' -html_review_style pythonic'];
    % Removed ' -regress_motion_per_run'... since there are so many short runs, and is eating up degrees of freedom
    
% Execute command
unix(afni_proc_cmd);
    